### PR TITLE
on-dhcp-proxy technical debt

### PR DESCRIPTION
**Pull request by heckj**

### CODE REVIEW

**Comment by jlongever** [comment]
Making reference to https://github.com/RackHD/specs/blob/master/proposed/Mock-Service-Testing.md since they are relevant.

**Comment by jlongever** [comment]
+1

**Comment by heckj** [comment]
@jlongever wasn't sure how to handle references to other work re: depdendencies. Especially as the location will move around as the specs go through their paces. I didn't see a link (markdown or otherwise) for the reference other than the comment in the PR, which will be pretty ephemeral. Is that intended?

**Comment by jlongever** [comment]
Good question.  Perhaps we don't need use direct links but maybe just tag the dependency in the .md file with the dependency filename?

**Pull request merged**
