### PR TITLE
on-core technical debt

### PR DESCRIPTION
**Pull request by heckj**

### CODE REVIEW

**Comment by jlongever** [comment]
Reference to unit-test proposal: https://github.com/RackHD/specs/blob/master/proposed/Mock-Service-Testing.md

**Comment by jlongever** [comment]
+1

**Comment by heckj** [comment]
@jlongever same question re: dependency reference on this one. I didn't have an obvious, non-moving reference to make re: a depdendency or related spec, and comments in a pull request are great for review, but pretty fundamentally ephemeral. Did you want to have a more "sticky" dependency or related work reference in the spec itself?

**Comment by jlongever** [comment]
Same answer I guess, just put the dependent spec filename in the .md?

**Pull request merged**
