### PR TITLE
adding MQTT research notes

### PR DESCRIPTION
**Pull request by heckj**
@jlongever I think mentioned MQTT, and while doing some weekend reading I stumbled across some articles on MQTT and NodeJS, including some effusive praise for the "mosca" library, so wanted to scribble that in here for future reference and reading

### CODE REVIEW

**Comment by benbp** [comment]
@heckj it was @zyoung51 who brought up MQTT.

**Comment by heckj** [comment]
erp

**Comment by zyoung51** [comment]
@heckj, @benbp What is your plan for topic discussion?

The discussion I had with Ben was regarding using Mosquitto (http://mosquitto.org/) and writing my own C program with minimal dependencies to create an embedded task runner for the discovery image.  The workflow author would understand that nodeid-domain based task runners will only accept shell command/downloadUrl tasks, which would make the c program simpler (dumber).  In that case, the scheduler RabbitMQ would talk to the nodeid-domain using MQTT (https://www.rabbitmq.com/mqtt.html).  I wrote some code to do it, but didn't like how the MQTT adapter in RabbitMQ was bound to a single exchange for all MQTT topics.  

I've used Mosquitto before, which is why I thought of it first, but the RabbitMQ C binding would probably make more sense (https://github.com/alanxz/rabbitmq-c) for an embedded client.

**Comment by heckj** [comment]
I just happened to run across the presentations this past week on MQTT and a Node.js library, and that Ben had mentioned some earlier conversations with you, but I didn’t know the details, so tacked in the references in case they were useful.

What to actually do and which libraries to use I’ll defer to you guys for what gives us the functionality we need/require but possibly has a lighter footprint than running a full AMQP server for the scenario of running inside a top-of-rack switch

**Pull request merged**
