### PR TITLE
Append Frey's v2 API spec

### PR DESCRIPTION
**Pull request by rolandpoulter**
I want to add an older version of John's v2 spec I had in an email. It includes his insight and some features I'd like to see for the UI.

### CODE REVIEW

**Comment by yyscamper** [comment]
@anhou @cgx027 @WangWinson

**Comment by yyscamper** [comment]
:+1:

**Comment by WangWinson** [comment]
:+1:

**Comment by rolandpoulter** [comment]
@brianparry

**Comment by brianparry** [comment]
:+1:

**Pull request merged**
