### PR TITLE
Mock Service Testing

### PR DESCRIPTION
**Pull request by jlongever**

### CODE REVIEW

**Comment by heckj** [comment]
what can we do to set up and run a set of integration tests that exercise all of the services and their dependencies running on a single VM - ideally something that can run via TravisCI - so that we have a set of regression and full-system interaction tests?

This improves on the unit tests and is valuable, but the gaping hole is anything related to an integration test for this open source project.

**Comment by heckj** [comment]
answering myself - addressing with https://github.com/RackHD/specs/pull/23

**Comment by heckj** [comment]
+1

**Comment by jlongever** [comment]
+1

**Pull request merged**
